### ISSUE TITLE
Plex not finding channels

### ISSUE THREAD

**Issue by justinglock40** [xiaodoudou/PlexIPTV#1]
Plex doesn't find the channels after connecting to the device? And if you press Scan Channels nothing happens still

**Comment by xiaodoudou** [comment]
Before that you should have the channels displayed.
Would love to make the "scan" feature emulate for Plex but I am afraid that so far until I get a real DVR box I have no idea what Plex expect here.
I will try to to spend more time on that; in conclusion regarding that button at this moment just avoid touching it... It is not required.

For your issue, you can check your channel directly from the browser `http://localhost:1234/lineup.json`, if it's empty it can comes from:

- Your local playlist is empty
- Your local playlist have a format that I haven't handle (If that the case provide it)

**Comment by jamesdisco** [comment]
Hi @xiaodoudou 
i'm having the same issue, here's my local playlist.
[iptv.zip](https://github.com/xiaodoudou/PlexIPTV/files/1998282/iptv.zip)
I checked http://localhost:1234/lineup.json and it show all my channels.
I let PlexIPTV run 1st time, create the local playlist and then disabled the remote one. I then cut the local list down to 300ish channels. My remote playlist has over 9000 channels and i know plex wont load that many.

**Comment by xiaodoudou** [comment]
I have remove your playlist to avoid anyone stole your access.
I will give a look and let you know.

**Comment by xiaodoudou** [comment]
Do you have any settings related to filter?

**Comment by jamesdisco** [comment]
> I have remove your playlist to avoid anyone stole your access.

Thanks, 
here's my settings
{
  "m3u8": {
    "local": "iptv.m3u8",
    "remote": "http://***"
  },
  "serverPort": 1233,
  "serverName": "PlexIPTV",
  "tunerCount": 3,
  "removeIfNotFoundOnFilter": false,
  "doNotPullRemotePlaylist": true,
  "filter": [
    {
      "name": ">>> US News",
      "channel": "1"
    },
    {
      "name": ">>> World News",
      "channel": "2"
    }
  ]
}

**Comment by scaronni** [comment]
Same issue here, can't find any channel. Maybe related to the length of the list?

`Enjoy your 27630 channels`

This is my `settings.json` file:

```
{
  "m3u8": {
    "local": "iptv.m3u8",
    "remote": "<redacted>"
  },
  "serverPort": "1234",
  "serverName": "Sky On Demand",
  "tunerCount": "1",
  "removeIfNotFoundOnFilter": false,
  "doNotPullRemotePlaylist": false,
  "filter": [
    {
      "name": ">>> US News",
      "channel": "1"
    },
    {
      "name": ">>> World News",
      "channel": "2"
    }
  ]
```

If I test with the 2 default channel list, it works fine.

**Comment by scaronni** [comment]
Just figured out that if I remove all lines with a comment from the download playlist, at least the red error bar disappears.

Before:
```
# cat iptv.m3u8 | wc -l
55260
```
![image](https://user-images.githubusercontent.com/1983966/39965900-54675160-56a2-11e8-9d6f-8ee4d4c09406.png)

After:
```
# sed -i -e '/^#/d' iptv.m3u8
# cat iptv.m3u8 | wc -l
27629
# sed -i -e 's/"doNotPullRemotePlaylist": false/"doNotPullRemotePlaylist": true/g' settings.json
```
![image](https://user-images.githubusercontent.com/1983966/39965921-c5fb5df8-56a2-11e8-9838-17afb562cedc.png)

**Comment by scaronni** [comment]
Things I've noticed; don't know if they are useful for debugging:

- The '#EXTINF` lines in my playlist all contain lots of tags and informations on the channel, and they all start with '#EXTINF:-1`, without a comma just after like in the bundled playlist.
- All entries in my playlist point to `.mkv` URLs, and not `.m3u8`.

**Comment by scaronni** [comment]
Sample entry (redacted):

```
#EXTINF:-1 tvg-id="" tvg-name="redacted" tvg-logo="http://redacted/redacted.jpg" group-title="CART- REDACTED",redacted
http://redacted:24000/movie/asdasd/8r13874b/jsaehdf7q8wf.mkv
```

**Comment by xiaodoudou** [comment]
I do replicate your issue; and even more it crash plex.
I think its related to the channel names; I will do some testing and let you know.

**Comment by xiaodoudou** [comment]
Identify the issue; it is linked to channel number.
Plex expect to be a string return by the DVR; will push a new version for it.

**Comment by xiaodoudou** [comment]
commit fcce466b38a2970ed10d5ec8033f4c7a2ca5d98c fix that

**Comment by xiaodoudou** [comment]
please try again with https://github.com/xiaodoudou/PlexIPTV/releases/tag/1.0.2

**Comment by xiaodoudou** [comment]
@scaronni you can use directly the binaries which avoid any build process. I will try to cover more the doc for the DVR install and build process.
Worst case you can directly run the app through the code source, as node don't really require compilation.

@justinglock40 I am thinking about it; I have done the filter feature to do that process manually.

**Comment by justinglock40** [comment]
How is that done with the filter? Plex doesn’t know where to load all channels. Some IPTV have “24/7 channels” that don’t exist on normal EPGs

**Comment by scaronni** [comment]
That would be nice.
Btw, it seems Plex is unable to add big playlists, testing now with another with 4893 channels and the EPG guide lookup / import just hang there.

**Comment by scaronni** [comment]
> @scaronni you can use directly the binaries which avoid any build process. I will try to cover more the doc for the DVR install and build process.
Worst case you can directly run the app through the code source, as node don't really require compilation.

Ok, thanks, was just trying to generate a binary. Doing the install with Ansible and the prebuilt binary.

**Comment by xiaodoudou** [comment]
That's the pity part from Plex DVR feature; I need to investigate how to handle none existant EPGs data.
Hardly advise to do they way I do: filter the channel you want as the DVR feature is region base...
For example my IPTV provider give me FR, Algerian, USA, and UK channels, I have filter 40 french channels.

**Comment by scaronni** [comment]
> Hardly advise to do they way I do: filter the channel you want as the DVR feature is region base...

Attempting that. My provider gave me 2 playlists, 1 for Video on Demand (27000+ entries), which does not seem to be covered at all by Plex, as it assumes the playlists are always TV based; and the other for Live TV which has channels from all over the world but mostly italian (4879 entries).

I guess I need to run multiple copies of PlexIPTV on multiple ports with multiple filters.

**Comment by xiaodoudou** [comment]
Don't use your VOD playlist with DVR feature isn't design for that; that should be more on IPTV plugin.

You could run multiple instance of PlexIPTV for all your channels (one by country); the issue (I don't know if you have the same), that my provider is limiting to only 1 stream allowed at time, so if you are using multiple instance you won't have the DVR channel limitation handle by Plex.

If your provider allows you like 4 viewer at the same time, and you plan to have 2 country, I advise you to limite the tunerCount to 2 for each instance.

**Comment by rvschuilenburg** [comment]
Just a heads up; running multiple with one per country won’t work. Plex is currently limiting you to choose one provider. So if you select a UK provider first and add another DVR device, it will force you to link it to the same UK provider.

**Comment by marshall12345** [comment]
i am having trouble with plex recognizing my channels .  all mine end in ts
they are all getting pulled into the iptv.m3u8 but they are not showing up in localhost:1234/lineup.json or in plex. thank you for your great work. i will be super happy if i can make this work

**Comment by marshall12345** [comment]
just a suggestion the default setting in the settings.json  should be "removeIfNotFoundOnFilter": false,   not true..   that's what was causing me problems.

**Comment by justinglock40** [comment]
Got channels to recognize and load into Plex but now I get errors could not tune channels

**Comment by marshall12345** [comment]
Yes im at the same problem. Plex does not recognize the guide from my iptv

**Comment by xiaodoudou** [comment]
@marshall12345 It's been set to true for the main reason @justinglock40 @marshall12345 having.
By default plex ask you to provided the Country, then the TV Provider, then it will match the channel number into their database.

That is why filtering and remapping channel is important; in my case I have remap 30 channel to their proper channel number and voila ~

If you don't do that approach the channel id will start at 80000 which correspond to none of any existing channel (I hope so xD).
Cheers

**Comment by globier** [comment]
I'm getting what looks to be the same problem as @justinglock40 The channels are found, the guide loads but when I try to play a stream plex states 
![image](https://user-images.githubusercontent.com/7547992/39987155-08d6a7ac-57b8-11e8-8b3b-f37d84eb96f0.png)

**Comment by jamesdisco** [comment]
I'm the same as @globier, unable to tune channels, at the moment i use telly and it works most of the time.

**Comment by globier** [comment]
I actually couldn't get Telly to work so hence I'm trying PlexIPTV

**Comment by xiaodoudou** [comment]
@globier @jamesdisco please create a separate issue and provide logs as example on homepage of that project.
Thank you
