### ISSUE TITLE
Rename channels

### ISSUE THREAD

**Issue by jamesdisco** [xiaodoudou/PlexIPTV#12]
Its great that we can allocate a channel no. to the channels. Would it be possible to change the channel name as plex isn't automatically matching the guide data to the channels.
My provider puts a country code in front of the channel name eg UK: BBC ONE HD it would be good if we could strip out the UK: part so that plex could match the channel names up better.

**Comment by xiaodoudou** [comment]
1.0.4 has that feature.

Here an example:
```
    {
      "name": ">>> US News",
      "channel": "1",
      "rename": "US News"
    },
```
