### ISSUE TITLE
Android Doesn't work

### ISSUE THREAD

**Issue by 12nick12** [xiaodoudou/PlexIPTV#14]
On Android it says The file associated with this item is not accessible by the server. Please verify that the file exists and the necessary drive is accessible."

**Comment by xiaodoudou** [comment]
Because the add isn't compile for android, sorry I have no plan to cover it ATM.

**Comment by 12nick12** [comment]
So Plex Android Client support is not in the works at all?

**Comment by xiaodoudou** [comment]
Oh my bad; I think you try to launch it on android.... sorry. 

It does work on client it depends of the stream; I am working on a remux atm to all the stream issue.

Does it work on desktop with that channel?

**Comment by 12nick12** [comment]
Yes I am. I'm using vaders and I added the ts to the end of the url to indicate ts

**Comment by xiaodoudou** [comment]
Hey @12nick12 , did recently had to watch a match into my phone; didn't got any issues; could you try with another android device?

**Comment by 12nick12** [comment]
It doesn't work on the newer app with the new ugly UI. I just downgraded to an older version of the apps it it works flawlessly. Gotta love Plex breaking things.

**Comment by 12nick12** [comment]
It's not working again. It must be something to do with my IPTV provider. It's works great on Roku and the Web. Thats more than enough for me.
