### ISSUE TITLE
Shows as offline

### ISSUE THREAD

**Issue by 12nick12** [xiaodoudou/PlexIPTV#15]
The DVR shows as offline, but still works. I know the telly dev is having the same issue. https://github.com/tombowditch/telly/pull/48

I'm sorry for so many requests, I just figured you'd like to know of them. It works enough for me at the moment.

**Comment by xiaodoudou** [comment]
If you restart Plex without restarting PlexIPTV you will see online as expected. 
![image](https://user-images.githubusercontent.com/1650357/40090097-484fe260-58e2-11e8-8978-b153fa770e95.png)

But in same situation Plex will make it listed as "Device not found" it's linked to some calls Plex is doing but I am not covering as I don't know what it does expect like the scan feature.

I may end-up to get a real DVR box to dump all its calls.
