### ISSUE TITLE
Awaiting channel scan

### ISSUE THREAD

**Issue by silkyclouds** [xiaodoudou/PlexIPTV#16]
Hi there,

I've installed PlexIPTV using docker and edited my settings.json file. 
Relaunched -> it pulled all my channels list to my localiptv.m3u8 file. 

But when I do launch plex -> enter the adresse manually -> it sees the tuner, but can't see any of the pulled channels. It keeps telling me awaiting channel scan. 

anyone here got the same issue ?

**Comment by silkyclouds** [comment]
hey guys,

any chance to get some support on this ?

**Comment by oliverjhyde** [comment]
I am also having this issue, I can see that PlexIPTV receives the request for a channel scan but it seems that Plex doesn't wait long enough for a reply
