### ISSUE TITLE
How to change the settings in Docker?

### ISSUE THREAD

**Issue by Skaronator** [xiaodoudou/PlexIPTV#4]
Currently there is no way to change the settings? Once it updates the container everything is gone.

You should add a persistent volume to the Dockerfile (/config) and store the settings.json in it.

**Comment by xiaodoudou** [comment]
I will look into it.

**Comment by xiaodoudou** [comment]
Change on 1.0.3 to allow you to pass the volume with `--volume [your path]:/opt/PlexIPTV/config `
See the following commit 64fac8eaf37c5acb818cd4db9b634b7a1dab895b
