### ISSUE TITLE
Allow specifying locations

### ISSUE THREAD

**Issue by scaronni** [xiaodoudou/PlexIPTV#5]
Thanks for updating the build instructions. :)

It would be nice to allow specifying locations for the various components when packaging for a Linux distribution, like log directory and settings file.

For example:
```
PlexIPTV.linux-x64 --logdir=/var/log/PlexIPTV --settings=/etc/PlexIPTV/settings.json
```
or
```
PlexIPTV.linux-x64 --logdir /var/log/PlexIPTV --settings /etc/PlexIPTV/settings.json
```

**Comment by xiaodoudou** [comment]
Will be available on 1.0.3 (currently building)
