### ISSUE TITLE
No Updates on Docker Hub

### ISSUE THREAD

**Issue by Skaronator** [xiaodoudou/PlexIPTV#7]
You need to link this Github Repo in Docker Hub. It'll automatically update new container versions.

It should look like this:

![image](https://user-images.githubusercontent.com/2886913/39971618-99618608-56fe-11e8-96d8-baac64514720.png)

Otherwise it'll never update the container to the new version.

**Comment by xiaodoudou** [comment]
I will look into it.

**Comment by xiaodoudou** [comment]
I have destroy the old repo, create a new one as advise the build is in progress.
Cheers,

**Comment by xiaodoudou** [comment]
![image](https://user-images.githubusercontent.com/1650357/39974765-65c864c4-575d-11e8-873e-a8e95c4eb92a.png)

Latest is up, doing all tags now.

**Comment by xiaodoudou** [comment]
All are up now, cheers
